# Generated by Django 3.2 on 2021-04-22 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content_Image',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('CImage', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Content_text',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('Cstr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goodID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('goodName', models.CharField(max_length=100)),
                ('goodImg', models.ImageField(upload_to='img')),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('state', models.CharField(max_length=10)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeweb.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeweb.address')),
                ('goodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeweb.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromID', models.CharField(max_length=20)),
                ('seq', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=10)),
                ('contentID', models.IntegerField(default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('priority', models.IntegerField()),
                ('goodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeweb.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('comTime', models.DateTimeField(auto_now_add=True)),
                ('goodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeweb.goods')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
