# Generated by Django 3.2 on 2021-04-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeweb', '0002_address_comments_content_image_content_text_detail_images_goods_messages_order_wants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('goodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeweb.goods')),
            ],
        ),
    ]
