# Generated by Django 3.2 on 2021-04-26 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tradeweb', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='msgTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
