# Generated by Django 3.2 on 2021-04-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeweb', '0005_messages_goodid'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
