# Generated by Django 3.2 on 2021-04-29 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeweb', '0006_goods_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeOrder',
            fields=[
                ('orderID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
