# Generated by Django 3.2 on 2021-04-29 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradeweb', '0007_beforeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='beforeOrder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tradeweb.beforeorder'),
            preserve_default=False,
        ),
    ]
